version: "3"

services:
  frontend:
    container_name: react-app
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./frontend:/app
    stdin_open: true
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
      - frontend
      - backend
    ports:
      - "3000:80"
  backend:
    container_name: spring-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: "${DB_URL}"
      SPRING_DATASOURCE_USERNAME: "${DB_USERNAME}"
      SPRING_DATASOURCE_PASSWORD: "${DB_PASSWORD}"
      SPRING_PROFILES_ACTIVE: dev
      CLOUD_AWS_S3_REGION: "${CLOUD_AWS_S3_REGION}"
      CLOUD_AWS_S3_URL: "${CLOUD_AWS_S3_URL}"
      CLOUD_AWS_S3_BUCKET: "${CLOUD_AWS_S3_BUCKET}"
      CLOUD_AWS_S3_ACCESS_KEY: "${CLOUD_AWS_S3_ACCESS_KEY}"
      CLOUD_AWS_S3_SECRET_KEY: "${CLOUD_AWS_S3_SECRET_KEY}"